version: '3.7'
services:
  mongo:
    image: mongo
    restart: on-failure
    ports:
      - 27017:27017
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
  mysql:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=scroot
      - MYSQL_USER=sc
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=scheduler
      - MYSQL_ONETIME_PASSWORD=true